apiVersion: v1
kind: Service
metadata:
  name: {{ include "game-application.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "game-application.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "game-application.name" . }}
