replicaCount: 2

image:
  repository: "935598635277.dkr.ecr.us-east-1.amazonaws.com/jenkins/game-application"
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  ENV: production
  PORT: "5000"

livenessProbe:
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  port: 5000

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5
  port: 5000

namespace: default
